branches:
  only:
    - dev
language: node_js
node_js:
- node
warnings_are_errors: false
before_install:
  - .travis/10_prebuild.sh $WEBHOOK_URL
script:
- cat .ssh/id_rsa.pub
- cd server
- npm install
- npm run test
- cd ..
- cd wa-client
- npm install
- npm run build
- npm run test
- cd ..

after_failure:
  - .travis/40_postbuild.sh failure $WEBHOOK_URL $BUILD_OUTPUT_URL

after_success:
  - .travis/push.sh
  - .travis/40_postbuild.sh success $WEBHOOK_URL $BUILD_OUTPUT_URL