language: node_js
node_js:
  - "node"
warnings_are_errors: false
script:
  - cd server
  - npm install
  - npm run build
  - npm run test
  - cd ..
  - cd client
  - npm install
  - npm run build
  - npm run test
  - cd ..