version: '3'
services:
  server:
    networks:
      - main
    build: server
    ports:
      - "8080:8080"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    restart: on-failure
  client_web:
    networks:
      - main
    build: wa-client
    depends_on:
      - client_mobile
      - server
    volumes:
      - /app/node_modules
      - ./wa-client:/app
      - apk:/var/www/:ro
    ports:
      - "8081:8081"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    restart: on-failure
  client_mobile:
    build: mobile
    volumes:
      - apk:/usr/src/app/android/app/build/outputs/apk/:rw
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    restart: on-failure

volumes:
  apk:
networks:
  main:
