version: '3'
services:
  server:
    networks:
      - main
    build: server
    ports:
      - "8080:8080"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    restart: on-failure
  client_web:
    networks:
      - main
    build: client
    depends_on:
      #      - client_mobile
      - server
    ports:
      - "8081:8081"
    volumes:
      - client:/usr/share/nginx/html:ro
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    restart: on-failure
#  client_mobile:
#    build: mobile
#    volumes:
#      - ./:/client
#      - /client/node_modules
#    logging:
#      driver: "json-file"
#      options:
#        max-size: "200k"
#        max-file: "10"
#    restart: on-failure

volumes:
  client:
networks:
  main:
