version: '3'
services:
  server:
    build: server
    ports:
      - "8080:80"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    restart: on-failure
  client_web:
    build: client
    ports:
      - "8081:80"
    volumes:
      - client:/usr/share/nginx/html:ro
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    restart: on-failure
  client_mobile:
    build: mobile
    volumes:
      - client:/usr/share/nginx/html:ro
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    restart: on-failure

volumes:
  client:

